### ISSUE TITLE
have a problem

### ISSUE THREAD

**Issue by dannyrbk** [blackdragonx61/Metin2-Extended-Safebox#1]
have a problem with system, only inventory I work for mee, the rest of the inventories do not go to put items in them

here is the ch1 and client syserr, help me please

syserr_client: https://pastebin.com/nAb3y1P2

syserr_ch1: https://pastebin.com/0pxZXFEF

**Comment by dannyrbk** [comment]
my mistake, sorry for the all issuse, the errors were caused by me.....the system work fine



thx man, you save me

**Comment by blackdragonx61** [comment]
:)
